language: node_js
node_js:
  - '0.12.7'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower grunt-cli'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages

after_script:
  - 'grunt test:unity' # or other command for build, run tests, etc
  - 'grunt test:integration' # or other command for build, run tests, etc
